    package dashboard;

import main.*;
import Config.config;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class AdminProduct extends javax.swing.JFrame {

    
      public AdminProduct() {
       
        if (config.loggedInAID <= 0) {
            JOptionPane.showMessageDialog(null,
                "You need to login first!",
                "DripHorizon - Login Required",
                JOptionPane.WARNING_MESSAGE);
            
            java.awt.EventQueue.invokeLater(() -> {
                new Login().setVisible(true);
            });
            
            this.dispose();
            return;
        }
        
        initComponents();
        
        displayUser();
        loadProfilePicture();
        accountsUser();
        loadProducts();
        
    }
       void loadProducts() {
    config con = new config();
    String sql = "SELECT id_buyers, Pname, BPrice, quantitys FROM tble_buyers"; 
    con.displayData(sql, tableProduct);
}
     
    
    
   void accountsUser() {
    config con = new config();
   
    String sql = "SELECT register_id, name, lastname, gmail, password, status, acstatus FROM tble_user"; 
    con.displayData(sql, tableProduct);
}
   
    
    void displayUser(){
        try {
            java.sql.Connection con = config.connectDB();
            String sql = "SELECT name, lastname,gmail FROM tble_user WHERE register_id = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, config.loggedInAID);

            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nm.setText("" + rs.getString("name"));
                ln.setText("" + rs.getString("lastname"));
               user.setText("" + rs.getString("gmail"));
            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
public static String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(password.getBytes("UTF-8"));

        StringBuilder hex = new StringBuilder();

        for (byte b : hash) {
            String h = Integer.toHexString(0xff & b);
            if (h.length() == 1) hex.append('0');
            hex.append(h);
        }

        return hex.toString();

    } catch (Exception e) {
        e.printStackTrace();
        return null;
    }
}
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ln = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Security = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(67, 80, 91));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel2.setText("Products");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 40));

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableProduct);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 490, 270));

        jPanel20.setBackground(new java.awt.Color(153, 153, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel1.setText("          Restack");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel20.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        jPanel3.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 120, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 490, 430));

        jPanel5.setBackground(new java.awt.Color(49, 87, 126));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 70, 20));
        jPanel6.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, 20));
        jPanel6.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 30));

        Profile.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 10)); // NOI18N
        Profile.setText("Change Profile");
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        jPanel6.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 20));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 150));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, 240));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Driphorizon");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled (Logo).png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 330, 150));

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jPanel15.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setText("          Sign Out");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 90));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel15.setText("       Help & Support");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 60));

        jPanel12.setBackground(new java.awt.Color(153, 153, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Security.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Security.setText("    Security Settings");
        Security.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SecurityMouseClicked(evt);
            }
        });
        jPanel12.add(Security, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 60));

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel8.setText("      Pending Accounts");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 60));

        jPanel13.setBackground(new java.awt.Color(153, 153, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel7.setText("             Products");
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 60));

        jPanel14.setBackground(new java.awt.Color(153, 153, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel3.setText("        Account Users");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, 60));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 470));

        jPanel16.setBackground(new java.awt.Color(0, 102, 102));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        jLabel22.setText("© 2026 DripHorizon. All rights");
        jPanel16.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soft-gradient-blue-green-background-vector-55526497.jpg"))); // NOI18N
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 400, 80));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        jLabel24.setText("reserved. Experience the drip in every step.");
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soft-gradient-blue-green-background-vector-55526497.jpg"))); // NOI18N
        jPanel17.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 80));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 350, 80));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soft-gradient-blue-green-background-vector-55526497.jpg"))); // NOI18N
        jPanel18.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 80));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 210, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        JFileChooser chooser = new JFileChooser();
    int result = chooser.showOpenDialog(this);

    if(result == JFileChooser.APPROVE_OPTION){
        File file = chooser.getSelectedFile();
        String path = file.getAbsolutePath();

       
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(
                jLabel6.getWidth(),
                jLabel6.getHeight(),
                Image.SCALE_SMOOTH);
        jLabel6.setIcon(new ImageIcon(img));

        
        try{
            Connection con = config.connectDB();
            String sql = "UPDATE tble_user SET profile_picture = ? WHERE register_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, path);
            pst.setInt(2, config.loggedInAID);

            pst.executeUpdate();
            pst.close();
            con.close();

            JOptionPane.showMessageDialog(this,"Profile picture updated!");
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
    }//GEN-LAST:event_ProfileMouseClicked

    private void SecurityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecurityMouseClicked
    javax.swing.JPasswordField passField = new javax.swing.JPasswordField();
javax.swing.JPasswordField confirmField = new javax.swing.JPasswordField();

javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0,1,5,5));
panel.add(new javax.swing.JLabel("Change your password:"));
panel.add(new javax.swing.JLabel("New Password:"));
panel.add(passField);
panel.add(new javax.swing.JLabel("Confirm Password:"));
panel.add(confirmField);

int result = javax.swing.JOptionPane.showConfirmDialog(
        null,
        panel,
        "Security Settings",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.PLAIN_MESSAGE
);

if(result == javax.swing.JOptionPane.OK_OPTION){

    String password = new String(passField.getPassword());
    String confirm = new String(confirmField.getPassword());

    if(password.isEmpty() || confirm.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this,"Please fill all fields!");
        return;
    }

    if(!password.equals(confirm)){
        javax.swing.JOptionPane.showMessageDialog(this,"Passwords do not match!");
        return;
    }

    try{

       
        String hashedPassword = register.hashPassword(password);

        java.sql.Connection con = config.connectDB();
        String sql = "UPDATE tble_user SET password=? WHERE register_id=?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, hashedPassword); 
        pst.setInt(2, config.loggedInAID);

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this,"Password updated successfully!");

        pst.close();
        con.close();

    }catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this,e);
    }
}
    }//GEN-LAST:event_SecurityMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
     
    int selectedRow = tableProduct.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Please select a product from the table first!", 
            "No Selection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    
    int id = Integer.parseInt(tableProduct.getValueAt(selectedRow, 0).toString());
    String currentName = tableProduct.getValueAt(selectedRow, 1).toString();
    double currentPrice = Double.parseDouble(tableProduct.getValueAt(selectedRow, 2).toString());
    int currentQty = Integer.parseInt(tableProduct.getValueAt(selectedRow, 3).toString());
    
   
    JTextField nameField = new JTextField(currentName);
    JTextField priceField = new JTextField(String.valueOf(currentPrice));
    JTextField addQtyField = new JTextField("0"); 
    JTextField newQtyField = new JTextField(String.valueOf(currentQty)); 
    
    JPanel panel = new JPanel(new GridLayout(0, 1, 5, 5));
    
    panel.add(new JLabel("Product Name:"));
    panel.add(nameField);
    
    panel.add(new JLabel("Price:"));
    panel.add(priceField);
    
    panel.add(new JLabel("Current Quantity: " + currentQty));
    panel.add(new JLabel("Add Quantity (Restock):"));
    panel.add(addQtyField);
    
    panel.add(new JLabel("Or Set New Quantity (Replace):"));
    panel.add(newQtyField);
    
    int result = JOptionPane.showConfirmDialog(
        this,
        panel,
        "Edit Product / Restock",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );
    
    if (result == JOptionPane.OK_OPTION) {
        String pname = nameField.getText().trim();
        String priceStr = priceField.getText().trim();
        String addQtyStr = addQtyField.getText().trim();
        String newQtyStr = newQtyField.getText().trim();
        
        if (pname.isEmpty() || priceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Product name and price are required!", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            double price = Double.parseDouble(priceStr);
            int finalQuantity = currentQty;
            
            if (!addQtyStr.equals("0") && !addQtyStr.isEmpty()) {
              
                int addQty = Integer.parseInt(addQtyStr);
                if (addQty < 0) {
                    JOptionPane.showMessageDialog(this, 
                        "Cannot add negative quantity!", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
                finalQuantity = currentQty + addQty;
            } else if (!newQtyStr.equals(String.valueOf(currentQty)) && !newQtyStr.isEmpty()) {
                
                finalQuantity = Integer.parseInt(newQtyStr);
            }
            
            if (price < 0 || finalQuantity < 0) {
                JOptionPane.showMessageDialog(this, 
                    "Price and quantity must be positive!", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Connection con = config.connectDB();
            String sql = "UPDATE tble_buyers SET Pname = ?, BPrice = ?, quantitys = ? WHERE id_buyers = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, pname);
            pst.setDouble(2, price);
            pst.setInt(3, finalQuantity);
            pst.setInt(4, id);
            
            int rowsAffected = pst.executeUpdate();
            
            if (rowsAffected > 0) {
                String message = "Product updated successfully!";
                if (!addQtyStr.equals("0") && !addQtyStr.isEmpty()) {
                    message = "Restocked! New quantity: " + finalQuantity;
                }
                JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
                
                loadProducts();
            }
            
            pst.close();
            con.close();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please enter valid numbers!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Database error: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        AdminUsers au = new AdminUsers();
        au.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
         Session.logout();
        javax.swing.JOptionPane.showMessageDialog(null, "Logged out successfully.");
        LandingPage landing = new LandingPage();
        landing.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       Admin a = new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
      HelpSupport a = new HelpSupport();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked
private void loadProfilePicture() {
    try {
        Connection con = config.connectDB();
        String sql = "SELECT profile_picture FROM tble_user WHERE register_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, config.loggedInAID);
        ResultSet rs = pst.executeQuery();

        if(rs.next()){
            String imgPath = rs.getString("profile_picture");
            if(imgPath != null && !imgPath.isEmpty()){
                ImageIcon icon = new ImageIcon(imgPath);
                Image img = icon.getImage().getScaledInstance(
                        jLabel6.getWidth(),
                        jLabel6.getHeight(),
                        Image.SCALE_SMOOTH);
                jLabel6.setIcon(new ImageIcon(img));
            }
        }

        rs.close();
        pst.close();
        con.close();
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel Security;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel nm;
    private javax.swing.JTable tableProduct;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
