    package dashboard;

import main.*;
import Config.config;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class AdminUsers extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseHistory
     */
       public AdminUsers() {
        // Check login using config.loggedInAID (same as user.java)
        if (config.loggedInAID <= 0) {
            JOptionPane.showMessageDialog(null,
                "You need to login first!",
                "DripHorizon - Login Required",
                JOptionPane.WARNING_MESSAGE);
            
            java.awt.EventQueue.invokeLater(() -> {
                new Login().setVisible(true);
            });
            
            // Close this window since login failed
            this.dispose();
            return;
        }
        
        initComponents();
         // Load data on startup
         // Show user name in header
        displayUser();
        loadProfilePicture();
        accountsUser();
        
    }
       
       public static String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(password.getBytes("UTF-8"));

        StringBuilder hex = new StringBuilder();

        for (byte b : hash) {
            String h = Integer.toHexString(0xff & b);
            if (h.length() == 1) hex.append('0');
            hex.append(h);
        }

        return hex.toString();

    } catch (Exception e) {
        e.printStackTrace();
        return null;
    }
}
      public void searchData() {
    config con = new config();
    String searchStr = jTextField1.getText().trim();
    
    // Explicitly select all columns EXCEPT profile_picture
    String sql = "SELECT register_id, name, lastname, gmail, password, status, acstatus "
               + "FROM tble_user WHERE "
               + "name LIKE '%" + searchStr + "%' OR "
               + "lastname LIKE '%" + searchStr + "%'";
    
    con.displayData(sql, tableuser);
}
    
    /**
     * Load purchase history from tble_buyer for current user
     * Columns: Product, Quantity, Total Price, Shipping, Payment, Date
     */
   void accountsUser() {
    config con = new config();
    // We list all columns explicitly but exclude 'profile_picture'
    String sql = "SELECT register_id, name, lastname, gmail, password, status, acstatus FROM tble_user"; 
    con.displayData(sql, tableuser);
}
   
    
    void displayUser(){
        try {
            java.sql.Connection con = config.connectDB();
            String sql = "SELECT name, lastname,gmail FROM tble_user WHERE register_id = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, config.loggedInAID);

            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nm.setText("" + rs.getString("name"));
                ln.setText("" + rs.getString("lastname"));
               user.setText("" + rs.getString("gmail"));
            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableuser = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ln = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        Security = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(67, 80, 91));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel2.setText("User Accounts");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 30));

        tableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableuser);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 490, 230));

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel4.setText("            Add");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 120, 60));

        jPanel19.setBackground(new java.awt.Color(153, 153, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel1.setText("          Delete");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel19.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        jPanel3.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 60));

        jPanel20.setBackground(new java.awt.Color(153, 153, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel3.setText("          Update");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel20.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        jPanel3.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 60));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 490, 430));

        jPanel5.setBackground(new java.awt.Color(49, 87, 126));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 70, 20));
        jPanel6.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, 20));
        jPanel6.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 30));

        Profile.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 10)); // NOI18N
        Profile.setText("Change Profile");
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        jPanel6.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 20));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 150));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, 240));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Driphorizon");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled (Logo).png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 330, 150));

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setText("          Sign Out");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 160, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 90));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(153, 153, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Security.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Security.setText("    Security Settings");
        Security.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SecurityMouseClicked(evt);
            }
        });
        jPanel12.add(Security, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 60));

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel8.setText("      Pending Accounts");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 60));

        jPanel13.setBackground(new java.awt.Color(153, 153, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel7.setText("             Products");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 60));

        jPanel14.setBackground(new java.awt.Color(153, 153, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel5.setText("        Account Users");
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, 60));

        jPanel21.setBackground(new java.awt.Color(153, 153, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel12.setText("       Help & Support");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jPanel7.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 60));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 470));

        jPanel16.setBackground(new java.awt.Color(0, 102, 102));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        jLabel22.setText("© 2026 DripHorizon. All rights");
        jPanel16.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soft-gradient-blue-green-background-vector-55526497.jpg"))); // NOI18N
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 400, 80));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        jLabel24.setText("reserved. Experience the drip in every step.");
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soft-gradient-blue-green-background-vector-55526497.jpg"))); // NOI18N
        jPanel17.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 80));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 350, 80));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soft-gradient-blue-green-background-vector-55526497.jpg"))); // NOI18N
        jPanel18.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 80));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 210, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        Session.logout();
        javax.swing.JOptionPane.showMessageDialog(null, "Logged out successfully.");
        LandingPage landing = new LandingPage();
        landing.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        JFileChooser chooser = new JFileChooser();
    int result = chooser.showOpenDialog(this);

    if(result == JFileChooser.APPROVE_OPTION){
        File file = chooser.getSelectedFile();
        String path = file.getAbsolutePath();

        // Show image in jLabel6
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(
                jLabel6.getWidth(),
                jLabel6.getHeight(),
                Image.SCALE_SMOOTH);
        jLabel6.setIcon(new ImageIcon(img));

        // Save path in database
        try{
            Connection con = config.connectDB();
            String sql = "UPDATE tble_user SET profile_picture = ? WHERE register_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, path);
            pst.setInt(2, config.loggedInAID);

            pst.executeUpdate();
            pst.close();
            con.close();

            JOptionPane.showMessageDialog(this,"Profile picture updated!");
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
    }//GEN-LAST:event_ProfileMouseClicked

    private void SecurityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecurityMouseClicked
     javax.swing.JPasswordField passField = new javax.swing.JPasswordField();
javax.swing.JPasswordField confirmField = new javax.swing.JPasswordField();

javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0,1,5,5));
panel.add(new javax.swing.JLabel("Change your password:"));
panel.add(new javax.swing.JLabel("New Password:"));
panel.add(passField);
panel.add(new javax.swing.JLabel("Confirm Password:"));
panel.add(confirmField);

int result = javax.swing.JOptionPane.showConfirmDialog(
        null,
        panel,
        "Security Settings",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.PLAIN_MESSAGE
);

if(result == javax.swing.JOptionPane.OK_OPTION){

    String password = new String(passField.getPassword());
    String confirm = new String(confirmField.getPassword());

    if(password.isEmpty() || confirm.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this,"Please fill all fields!");
        return;
    }

    if(!password.equals(confirm)){
        javax.swing.JOptionPane.showMessageDialog(this,"Passwords do not match!");
        return;
    }

    try{

        // HASH THE PASSWORD
        String hashedPassword = register.hashPassword(password);

        java.sql.Connection con = config.connectDB();
        String sql = "UPDATE tble_user SET password=? WHERE register_id=?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, hashedPassword); // save hashed password
        pst.setInt(2, config.loggedInAID);

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this,"Password updated successfully!");

        pst.close();
        con.close();

    }catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this,e);
    }
}
    }//GEN-LAST:event_SecurityMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
     int selectedRow = tableuser.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user to delete.");
        return;
    }

    // Get the User ID and Email from the table
    int id = Integer.parseInt(tableuser.getValueAt(selectedRow, 0).toString());
    String userEmail = tableuser.getValueAt(selectedRow, 3).toString(); 

    int confirm = JOptionPane.showConfirmDialog(this,
            "Delete this user? This will also remove their purchases and contact messages.",
            "Confirm Full Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

    if (confirm != JOptionPane.YES_OPTION) return;

    try {
        config con = new config();
        java.sql.Connection connection = con.connectDB();
        connection.setAutoCommit(false); // Start transaction

        try {
            // 1. Delete from tble_buyer using 'user_id' (NOT buyer_id)
            String sqlBuyer = "DELETE FROM tble_buyer WHERE user_id = ?";
            try (java.sql.PreparedStatement pstBuyer = connection.prepareStatement(sqlBuyer)) {
                pstBuyer.setString(1, String.valueOf(id)); // user_id is TEXT in your schema
                pstBuyer.executeUpdate();
            }

            // 2. Delete from tble_ContactUs using 'Cemail'
            String sqlContact = "DELETE FROM tble_ContactUs WHERE Cemail = ?";
            try (java.sql.PreparedStatement pstContact = connection.prepareStatement(sqlContact)) {
                pstContact.setString(1, userEmail);
                pstContact.executeUpdate();
            }

            // 3. Finally, delete from tble_user using 'register_id'
            String sqlUser = "DELETE FROM tble_user WHERE register_id = ?";
            try (java.sql.PreparedStatement pstUser = connection.prepareStatement(sqlUser)) {
                pstUser.setInt(1, id);
                pstUser.executeUpdate();
            }

            connection.commit(); // Save all changes
            JOptionPane.showMessageDialog(this, "User and all related records deleted!");

        } catch (SQLException ex) {
            connection.rollback(); // Undo if any step fails
            throw ex;
        } finally {
            connection.setAutoCommit(true);
            connection.close();
        }

        // Refresh the table view
        accountsUser(); 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error during deletion: " + e.getMessage());
    }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      int selectedRow = tableuser.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select user to update.");
        return;
    }

    try {
        int id = Integer.parseInt(tableuser.getValueAt(selectedRow, 0).toString());

        JTextField txtName = new JTextField(tableuser.getValueAt(selectedRow, 1).toString());
        JTextField txtLastname = new JTextField(tableuser.getValueAt(selectedRow, 2).toString());
        JTextField txtgmail = new JTextField(tableuser.getValueAt(selectedRow, 3).toString());
        JTextField txtPassword = new JTextField(); // blank for new password
        JTextField txtStatus = new JTextField(tableuser.getValueAt(selectedRow, 5).toString());
        JTextField txtAcstatus = new JTextField(tableuser.getValueAt(selectedRow, 6).toString());

        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.add(new JLabel("First Name:")); panel.add(txtName);
        panel.add(new JLabel("Last Name:")); panel.add(txtLastname);
        panel.add(new JLabel("Gmail:")); panel.add(txtgmail);
        panel.add(new JLabel("New Password:")); panel.add(txtPassword);
        panel.add(new JLabel("Status:")); panel.add(txtStatus);
        panel.add(new JLabel("Account Status:")); panel.add(txtAcstatus);

        int result = JOptionPane.showConfirmDialog(this, panel,
                "Update User: " + tableuser.getValueAt(selectedRow, 1),
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            // Check for duplicate Gmail
            config con = new config();
            Connection connection = con.connectDB();

            String checkSql = "SELECT * FROM tble_user WHERE gmail=? AND register_id != ?";
            PreparedStatement checkPst = connection.prepareStatement(checkSql);
            checkPst.setString(1, txtgmail.getText());
            checkPst.setInt(2, id);
            ResultSet rs = checkPst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Gmail already used by another account!");
                return;
            }

            // Hash password only if user entered something
            String passwordToSave = tableuser.getValueAt(selectedRow, 4).toString(); // current password
            if (!txtPassword.getText().isEmpty()) {
                passwordToSave = register.hashPassword(txtPassword.getText());
            }

            // Update user
            String sql = "UPDATE tble_user SET name=?, lastname=?, gmail=?, password=?, status=?, acstatus=? WHERE register_id=?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, txtName.getText());
            pst.setString(2, txtLastname.getText());
            pst.setString(3, txtgmail.getText());
            pst.setString(4, passwordToSave);
            pst.setString(5, txtStatus.getText());
            pst.setString(6, txtAcstatus.getText());
            pst.setInt(7, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "User Updated Successfully!");

            pst.close();
            connection.close();

            // Refresh table
            accountsUser();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating user: " + e.getMessage());
    }
   
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
      try {
        JTextField txtName = new JTextField();
        JTextField txtLastname = new JTextField();
        JTextField txtgmail = new JTextField();
        JTextField txtPassword = new JTextField();

        String[] roleOptions = {"Admin", "User"};
        JComboBox<String> cbStatus = new JComboBox<>(roleOptions);

        String[] acOptions = {"Active", "Inactive"};
        JComboBox<String> cbAcstatus = new JComboBox<>(acOptions);

        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.add(new JLabel("First Name:")); panel.add(txtName);
        panel.add(new JLabel("Last Name:")); panel.add(txtLastname);
        panel.add(new JLabel("Gmail:")); panel.add(txtgmail);
        panel.add(new JLabel("Password:")); panel.add(txtPassword);
        panel.add(new JLabel("Role:")); panel.add(cbStatus);
        panel.add(new JLabel("Account Status:")); panel.add(cbAcstatus);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add New User",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            // Validate required fields
            if (txtName.getText().isEmpty() || txtLastname.getText().isEmpty() ||
                txtgmail.getText().isEmpty() || txtPassword.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields are required!");
                return;
            }

            // Optional: Validate Gmail format
            if (!txtgmail.getText().matches("^[\\w-.]+@[\\w-]+\\.[a-z]{2,}$")) {
                JOptionPane.showMessageDialog(this, "Invalid Gmail format!");
                return;
            }

            config con = new config();
            Connection connection = con.connectDB();

            // Check for duplicate Gmail
            String checkSql = "SELECT * FROM tble_user WHERE gmail = ?";
            PreparedStatement checkPst = connection.prepareStatement(checkSql);
            checkPst.setString(1, txtgmail.getText());
            ResultSet rs = checkPst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Gmail already exists! Please use another Gmail.");
                return;
            }

            // Hash password
            String hashedPassword = register.hashPassword(txtPassword.getText());

            // Insert new user
            String sql = "INSERT INTO tble_user (name, lastname, gmail, password, status, acstatus) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, txtName.getText());
            pst.setString(2, txtLastname.getText());
            pst.setString(3, txtgmail.getText());
            pst.setString(4, hashedPassword);
            pst.setString(5, cbStatus.getSelectedItem().toString());
            pst.setString(6, cbAcstatus.getSelectedItem().toString());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "User Added Successfully!");

            pst.close();
            connection.close();

            // Refresh table
            accountsUser();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding user: " + e.getMessage());
    }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        searchData();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        AdminProduct ap = new AdminProduct();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Admin a = new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
       HelpSupport a = new HelpSupport();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked
private void loadProfilePicture() {
    try {
        Connection con = config.connectDB();
        String sql = "SELECT profile_picture FROM tble_user WHERE register_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, config.loggedInAID);
        ResultSet rs = pst.executeQuery();

        if(rs.next()){
            String imgPath = rs.getString("profile_picture");
            if(imgPath != null && !imgPath.isEmpty()){
                ImageIcon icon = new ImageIcon(imgPath);
                Image img = icon.getImage().getScaledInstance(
                        jLabel6.getWidth(),
                        jLabel6.getHeight(),
                        Image.SCALE_SMOOTH);
                jLabel6.setIcon(new ImageIcon(img));
            }
        }

        rs.close();
        pst.close();
        con.close();
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel Security;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel nm;
    private javax.swing.JTable tableuser;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
