package main;

import Config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class PurchaseHistory extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseHistory
     */
       public PurchaseHistory() {
        // Check login using config.loggedInAID (same as user.java)
        if (config.loggedInAID <= 0) {
            JOptionPane.showMessageDialog(null,
                "You need to login first!",
                "DripHorizon - Login Required",
                JOptionPane.WARNING_MESSAGE);
            
            java.awt.EventQueue.invokeLater(() -> {
                new Login().setVisible(true);
            });
            
            // Close this window since login failed
            this.dispose();
            return;
        }
        
        initComponents();
        loadPurchaseHistory(); // Load data on startup
        displayUserName(); // Show user name in header
    }
    
    /**
     * Load purchase history from tble_buyer for current user
     * Columns: Product, Quantity, Total Price, Shipping, Payment, Date
     */
    private void loadPurchaseHistory() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing data
        
        // Set column headers (6 columns - no buyer_id)
        model.setColumnIdentifiers(new String[] {
            "Product", 
            "Quantity", 
            "Total Price", 
            "Shipping", 
            "Payment", 
            "Date"
        });
        
        String sql = "SELECT product, quantity, total_price, " +
                    "shipping_method, payment_method, purchase_date " +
                    "FROM tble_buyer WHERE user_id = ? ORDER BY purchase_date DESC";
        
        config con = new config();
        
        try (Connection cn = con.connectDB();
             PreparedStatement pst = cn.prepareStatement(sql)) {
            
            pst.setInt(1, config.loggedInAID); // Current logged in user ID
            
            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("product"),           // Product name
                        rs.getInt("quantity"),              // Quantity
                        String.format("₱%.2f", rs.getDouble("total_price")), // Total Price
                        rs.getString("shipping_method"),    // Shipping
                        rs.getString("payment_method"),     // Payment
                        rs.getString("purchase_date")      // Date
                    });
                }
            }
            
            // Show message if no purchases found
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, 
                    "No purchase history found.", 
                    "Purchase History", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error loading purchase history: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Display current user name in header
     */
    private void displayUserName() {
        try {
            java.sql.Connection con = config.connectDB();
            String sql = "SELECT name FROM tble_user WHERE register_id = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, config.loggedInAID);
            java.sql.ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                String fullName = rs.getString("name");
                String firstName = fullName.split(" ")[0];
                Name.setText("Welcome, " + firstName);
            }
            
            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            System.err.println("Error loading user name: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 320, 130));

        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("   ");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 100, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       UserDashboard ud = new UserDashboard();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
